// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKFGB3AbOVEMhC9_8wgBFdoUyEEtBQt8',
    appId: '1:336210526974:web:ec188646365506b003dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    authDomain: 'advert-6adbc.firebaseapp.com',
    storageBucket: 'advert-6adbc.appspot.com',
    measurementId: 'G-H4PCXRQZY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7auF0yGNgxtcfueElA_YTSxglUQPehNc',
    appId: '1:336210526974:android:13681455dda97d2803dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    storageBucket: 'advert-6adbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZ6HT-j7vnUbLU8fyaq80-tqQ0n08rYY',
    appId: '1:336210526974:ios:d1873ea865dafa6f03dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    storageBucket: 'advert-6adbc.appspot.com',
    iosClientId: '336210526974-vcl2l31nc0t1nf9l37ljsiuqbfs6ahjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZ6HT-j7vnUbLU8fyaq80-tqQ0n08rYY',
    appId: '1:336210526974:ios:e602b0b4d63e5b1703dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    storageBucket: 'advert-6adbc.appspot.com',
    iosClientId: '336210526974-madjbk6jhacqbh1j7uaqpjao6mt3b9o2.apps.googleusercontent.com',
    iosBundleId: 'com.example.advert.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKFGB3AbOVEMhC9_8wgBFdoUyEEtBQt8',
    appId: '1:336210526974:web:dc98f10736f31e9c03dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    authDomain: 'advert-6adbc.firebaseapp.com',
    storageBucket: 'advert-6adbc.appspot.com',
    measurementId: 'G-YBY3Z6QQ9B',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCiKFGB3AbOVEMhC9_8wgBFdoUyEEtBQt8',
    appId: '1:336210526974:web:a43e14fa0f5121b703dbaf',
    messagingSenderId: '336210526974',
    projectId: 'advert-6adbc',
    authDomain: 'advert-6adbc.firebaseapp.com',
    storageBucket: 'advert-6adbc.appspot.com',
    measurementId: 'G-0EGRN60N3F',
  );
}
